name: Spring Boot CI with Two Images

on:
  push:
    branches:
      - main  # Chạy khi push vào nhánh main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Bước 1: Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Thiết lập Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Bước 3: Build hello-spring-k8s với Maven
      - name: Build hello-spring-k8s
        working-directory: ./spring-k8s
        run: mvn clean package -DskipTests

      # Bước 4: Build hello-caller với Maven (nếu là Java)
      - name: Build hello-caller
        working-directory: ./caller
        run: mvn clean package -DskipTests

      # Bước 5: Build và push Docker image cho hello-spring-k8s
      - name: Build and Push hello-spring-k8s Image
        working-directory: ./spring-k8s
        run: |
          docker build -t kiet123123/hello-spring-k8s:${{ github.sha }} .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push kiet123123/hello-spring-k8s:${{ github.sha }}
          docker tag kiet123123/hello-spring-k8s:${{ github.sha }} kiet123123/hello-spring-k8s:latest
          docker push kiet123123/hello-spring-k8s:latest

      # Bước 6: Build và push Docker image cho hello-caller
      - name: Build and Push hello-caller Image
        working-directory: ./caller
        run: |
          docker build -t kiet123123/hello-caller:${{ github.sha }} .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push kiet123123/hello-caller:${{ github.sha }}
          docker tag kiet123123/hello-caller:${{ github.sha }} kiet123123/hello-caller:latest
          docker push kiet123123/hello-caller:latest